# Generated by Django 5.2a1 on 2025-02-08 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)], verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Изображение блюда')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='category.category', verbose_name='Категории блюд')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ('name',),
            },
        ),
    ]
