# Generated by Django 5.2a1 on 2025-02-08 16:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)], verbose_name='Slug')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время заказа')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='pending', max_length=7, verbose_name='Статус заказа')),
                ('dish', models.ManyToManyField(to='dish.dish')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table', to='table.table', verbose_name='Столы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['-date', '-time'], name='orders_orde_date_e6480c_idx')],
            },
        ),
    ]
