# Generated by Django 5.2a1 on 2025-02-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dish',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='table_number',
        ),
    ]
