# Generated by Django 5.2a1 on 2025-02-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_alter_dish_category_alter_dish_price'),
        ('orders', '0002_rename_dish_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='dish.dish', verbose_name='Список блюд'),
        ),
    ]
